// --- START OF FILE utils/paymentVerification.js (NEW FILE) ---

const crypto = require('crypto');

/**
 * Verifies the Razorpay payment signature.
 * IMPORTANT: This requires you to be using Razorpay's Orders API on your backend
 * to generate an order_id *before* initializing the frontend checkout.
 * If you are NOT using the Orders API, signature verification cannot be done this way.
 *
 * @param {string} razorpay_order_id - The order_id generated by your backend via Razorpay Orders API.
 * @param {string} razorpay_payment_id - The payment_id received from Razorpay frontend callback.
 * @param {string} razorpay_signature - The signature received from Razorpay frontend callback.
 * @returns {boolean} - True if the signature is valid, false otherwise.
 */
const verifyRazorpaySignature = (razorpay_order_id, razorpay_payment_id, razorpay_signature) => {
  // Ensure you have the Razorpay Secret Key in your environment variables
  const razorpaySecret = process.env.RAZORPAY_KEY_SECRET;

  if (!razorpaySecret) {
    console.error("CRITICAL: Razorpay Secret Key is missing in environment variables!");
    return false; // Cannot verify without the secret
  }

  if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
    console.warn("Missing parameters for Razorpay signature verification.");
    return false;
  }

  // The text to hash is order_id + "|" + payment_id
  const text = razorpay_order_id + "|" + razorpay_payment_id;

  // Create an HMAC SHA256 hash using the secret key
  const generated_signature = crypto
    .createHmac('sha256', razorpaySecret)
    .update(text)
    .digest('hex');

  // Compare the generated signature with the one received from Razorpay
  if (generated_signature === razorpay_signature) {
    console.log("Razorpay Signature Verified: TRUE");
    return true;
  } else {
    console.log("Razorpay Signature Verified: FALSE");
    console.log("Generated:", generated_signature);
    console.log("Received: ", razorpay_signature);
    return false;
  }
};

module.exports = {
  verifyRazorpaySignature,
};

// --- END OF FILE utils/paymentVerification.js ---